server:
  port: 2023

spring:
  application:
    name: User-Service
  datasource:
    url: jdbc:mysql://localhost:3306/userService
    username: root
    password: Saurabh@1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#Adding config-Server
  config:
    import: optional:configserver:http://localhost:8085/

#actuator configuration
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint.info.enabled: true
  endpoint:
    health:
      show-details: always

#resilience 4j
resilience4j:
  circuitbreaker:
    instances:
      ratingUserBreaker :
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based

#Retry Configuration
  retry:
    instances:
      ratingUserBreaker :
        max-attempts: 3
        wait-duration: 5s
#RateLimiter Configuration
  ratelimiter:
    instances:
      ratingUserLimiter :
        limit-for-period: 2
        limit-refresh-period: 4s
        timeout-duration: 0s








