server:
  port: 2025
spring:
  application:
    name: Rating_Service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingService
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
