server:
  port: 2025
spring:
  application:
    name: Rating-Service
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingService

  #Adding config-Server
  config:
    import: optional:configserver:http://localhost:8085/

