server:
  port: 2024
spring:
  application:
    name: Hotel-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelService
    username: postgres
    password: Saurabh@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  #Adding config-Server
  config:
    import: optional:configserver:http://localhost:8085/