server:
  port: 2024
spring:
  application:
    name: Hotel-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelService
    username: postgres
    password: Saurabh@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Added in order To register with eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka